baseURL = "/"
languageCode = "en-us"
title = "Cache Valley AI Community"
buildFuture = true

[params]
description = "A small AI community in Logan, Utah. We meet up for lunch every so often and hang out on Discord in between."
github = "https://github.com/nodrej/cache-valley-ai-community"

[params.Social]
twitter = ""

[markup]
[markup.goldmark.renderer]
unsafe = true

[minify]
disableHTML = false
disableCSS = false
disableJS = false

[permalinks]
posts = "/posts/:slug/"
page = "/:slug/"

[outputs]
home = ["html", "rss"]
section = ["html", "rss"]

[sitemap]
changeFreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[[params.navlinks]]
name = "about/"
url = "/about/"

[[params.navlinks]]
name = "community/"
url = "/#community"

[[params.navlinks]]
name = "topics/"
url = "/#topics"

[[params.navlinks]]
name = "posts/"
url = "/posts/"

[[params.navlinks]]
name = "faq/"
url = "/#faq"
